site: Hermana Possié

timezone: America/Denver

url: https://coban.possiefamily.com
baseurl:

#staticman_url: https://staticman-ubun2junky.herokuapp.com/v3/entry/github/ubun2Junky/coban_mission/gh-pages/comments
staticman_url: https://staticman-ubun2junky.fly.dev/v3/entry/github/ubun2Junky/coban_mission/gh-pages/comments

reCaptcha:
    enabled: false
    siteKey:
    secret:
    # siteKey: 6Le4MQkhAAAAAPZqWcfqsnYjga7X6xszjUHDSlf5
    # secret: NyNe9Nrit274m9IaaZrs50ovOth37qJlvnJufMnYVjRQnKoPThQNRYE34JYw+EL4aQbyeZSPihtCXccjMI8evJ5oaQOdanfUT0ZipSfApAQOBJw7jxIb2RIhts97Nf+nUB/FyiRZ6VNd+n9qh17nRjsVCXx4jDF5prv6Sgauq0Qntdu4ODNP0RiVjIUneXX8rZ1xIHxlVwK38ykNsN+INhOo9w605qjz6KY5ISWGLHOPJ8+JAZAj08swf2MyG9LrW/mPqAeSV9/dCfHrKdnvMm3ADr202CC+cluBJxImRBObHr8N7GekIbZ4DSDgOL5yM+cFloxEtC/ml9VBpoGRZw==

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

paginate: 6
paginate_path: "/blog/page:num/"
